apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment_name | quote }}
  labels:
    app: {{ .Values.app_name | quote }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app_name | quote }}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: {{ .Values.app_name | quote }}
    spec:
      containers:
      - image: {{ .Values.image | quote }}
        name: main
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: regcred