apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc_name | quote }}
  labels:
    run: {{ .Values.app_name | quote }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.svc_port }}
    protocol: TCP
  selector:
    run: {{ .Values.app_name | quote }}
